            # util.savePhasePerCycleSpiral(centerPose_img,phase, imageFolder+"pytorch_"+'RatAll_F1_percycle_'+str(step)+'.png', fig=None)
            # # 				util.savePhaseRainbowPlot2(centerPose_img,phase, imageFolder+'RatAll_F2_'+str(step)+'.png', fig=None)
            # util.save1000PhaseSpiral(centerPose_img,phase, imageFolder+"pytorch_"+'RatAll_F1_1000_'+str(step)+'.png', fig=None)
            # util.saveFirstHalfPhaseSpiral(centerPose_img,phase, imageFolder+"pytorch_"+'RatAll_F1_firsthalf_'+str(step)+'.png', fig=None)
            # util.saveLateHalfPhaseSpiral(centerPose_img,phase, imageFolder+"pytorch_"+'RatAll_F1_latehalf_'+str(step)+'.png', fig=None)